name: Build and deploy an app to AKS

on:
  push:
    branches: ["master"]
  workflow_dispatch:

env:
  AZURE_CONTAINER_REGISTRY: "your-azure-container-registry"
  CONTAINER_NAME: "your-container-name"
  RESOURCE_GROUP: "your-resource-group"
  CLUSTER_NAME: "your-cluster-name"
  DEPLOYMENT_MANIFEST_PATH: "your-deployment-manifest-path"

jobs:
  buildImage:
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    steps:
      # Step 1: Code checkout
      - uses: actions/checkout@v4

      # ✅ Step 2: Azure Login via OIDC
      - name: Azure Login via OIDC
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          allow-no-subscriptions: true
          enable-AzPSSession: true

      # ✅ Step 3: Get secrets from Azure Key Vault
      - name: Get secrets from Azure Key Vault
        uses: azure/get-keyvault-secrets@v1
        with:
          keyvault: "key-valte"
          secrets: |
            AZURE-CLIENT-ID
            AZURE-TENANT-ID
            AZURE-SUBSCRIPTION-ID

      # ✅ Step 4: Echo secrets (debugging ke liye optional)
      - name: Echo secrets
        run: |
          echo "Client ID: ${{ env.AZURE-CLIENT-ID }}"
          echo "Tenant ID: ${{ env.AZURE-TENANT-ID }}"
          echo "Subscription ID: ${{ env.AZURE-SUBSCRIPTION-ID }}"
