name: Build and deploy an app to AKS

on:
  push:
    branches: ["master"]
  workflow_dispatch:

env:
  AZURE_CONTAINER_REGISTRY: "your-azure-container-registry"
  CONTAINER_NAME: "your-container-name"
  RESOURCE_GROUP: "your-resource-group"
  CLUSTER_NAME: "your-cluster-name"
  DEPLOYMENT_MANIFEST_PATH: "your-deployment-manifest-path"

jobs:
  buildImage:
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    steps:
      # Step 1: Code Checkout
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Get secrets from Azure Key Vault
      - name: Get secrets from Azure Key Vault
        id: get-secrets
        uses: azure/get-keyvault-secrets@v1
        with:
          keyvault: "key-valte"
          secrets: |
            AZURE-CLIENT-ID
            AZURE-TENANT-ID
            AZURE-SUBSCRIPTION-ID

      # ✅ Step 3: Export Secrets to Environment
      - name: Export Secrets as ENV
        run: |
          echo "AZURE_CLIENT_ID=${{ steps.get-secrets.outputs.AZURE-CLIENT-ID }}" >> $GITHUB_ENV
          echo "AZURE_TENANT_ID=${{ steps.get-secrets.outputs.AZURE-TENANT-ID }}" >> $GITHUB_ENV
          echo "AZURE_SUBSCRIPTION_ID=${{ steps.get-secrets.outputs.AZURE-SUBSCRIPTION-ID }}" >> $GITHUB_ENV

      # ✅ Step 4: Azure Login using exported secrets
      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ env.AZURE_CLIENT_ID }}
          tenant-id: ${{ env.AZURE_TENANT_ID }}
          subscription-id: ${{ env.AZURE_SUBSCRIPTION_ID }}
          enable-AzPSSession: true
          allow-no-subscriptions: false

      # Optional: Debug secrets
      - name: Echo for Debug
        run: |
          echo "CLIENT: ${{ env.AZURE_CLIENT_ID }}"
          echo "TENANT: ${{ env.AZURE_TENANT_ID }}"
          echo "SUBSCRIPTION: ${{ env.AZURE_SUBSCRIPTION_ID }}"
