name: Build and deploy an app to AKS

on:
  push:
    branches: ["master"]
  workflow_dispatch:

env:
  AZURE_CONTAINER_REGISTRY: "your-azure-container-registry"
  CONTAINER_NAME: "your-container-name"
  RESOURCE_GROUP: "your-resource-group"
  CLUSTER_NAME: "your-cluster-name"
  DEPLOYMENT_MANIFEST_PATH: "your-deployment-manifest-path"

jobs:
  buildImage:
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    steps:
      # Checks out the repository this file is in
      - uses: actions/checkout@v4

- name: Azure Login via OIDC
  uses: azure/login@v1
  with:
    client-id: ${{ secrets.AZURE_CLIENT_ID }}
    tenant-id: ${{ secrets.AZURE_TENANT_ID }}
    subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    allow-no-subscriptions: true
    enable-AzPSSession: true

- name: Get secrets from Azure Key Vault
  uses: azure/get-keyvault-secrets@v1
  with:
    keyvault: "key-valte"
    secrets: |
      AZURE-CLIENT-ID
      AZURE-TENANT-ID
      AZURE-SUBSCRIPTION-ID
  env:
    AZURE_CLIENT_ID: ${{ secrets.AZURE-CLIENT-ID }}
    AZURE_TENANT_ID: ${{ secrets.AZURE-TENANT-ID }}
    AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE-SUBSCRIPTION-ID }}
