name: Build and deploy an app to AKS

on:
  push:
    branches: ["master"]
  workflow_dispatch:

env:
  AZURE_CONTAINER_REGISTRY: "your-azure-container-registry"
  CONTAINER_NAME: "your-container-name"
  RESOURCE_GROUP: "your-resource-group"
  CLUSTER_NAME: "your-cluster-name"
  DEPLOYMENT_MANIFEST_PATH: "your-deployment-manifest-path"

jobs:
  buildImage:
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    steps:
      # Step 1: Code Checkout
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Get secrets from Azure Key Vault
      - name: Get secrets from Azure Key Vault
        uses: azure/get-keyvault-secrets@v1
        with:
          keyvault: "key-valte"
          secrets: |
            AZURE-CLIENT-ID
            AZURE-TENANT-ID
            AZURE-SUBSCRIPTION-ID

      # Step 3: Azure Login using OIDC and secrets from Key Vault
      - name: Azure Login via OIDC
        uses: azure/login@v1
        with:
          client-id: ${{ env.AZURE-CLIENT-ID }}
          tenant-id: ${{ env.AZURE-TENANT-ID }}
          subscription-id: ${{ env.AZURE-SUBSCRIPTION-ID }}
          enable-AzPSSession: true
          allow-no-subscriptions: false

      # (Optional) Step 4: Echo for debugging
      - name: Echo for Debug
        run: |
          echo "CLIENT: ${{ env.AZURE-CLIENT-ID }}"
          echo "TENANT: ${{ env.AZURE-TENANT-ID }}"
          echo "SUBSCRIPTION: ${{ env.AZURE-SUBSCRIPTION-ID }}"
